### ISSUE TITLE
The requested accessory 'Renault ZOE' was not registered by any plugin

### ISSUE THREAD

**Issue by apographon** [brownad/homebridge-zoe#2]
Just tried the Plugin. 

[2020-4-19 22:18:49] Error: The requested accessory 'Renault ZOE' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by brownad** [comment]
Did you add config to config.json?

Also it may not work for you since Renault switched over to latest API a couple of weeks ago.  Am yet to make the changes
